AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for dynamic config containers demo
Resources:
  DemoVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/micharizdemo-scratchbucket/11d3ef062ea44252797b70a552bcc7ba.template
      Parameters:
        VpcName:
          Fn::Sub: ${AWS::StackName}-VPC
  DemoSSMParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/micharizdemo-scratchbucket/afb4b5b9a00dd0e4df2c73a151c9dcfb.template
      Parameters:
        DefaultImageUrl: https://micharizdemo.s3-eu-west-1.amazonaws.com/ssmparam-dynamic-config/images/CaptAmerica.png
        ConfigVersionParamName:
          Fn::Sub: /${AWS::StackName}/configVersion
        ImageUrlParamName:
          Fn::Sub: /${AWS::StackName}/imageUrl
        GreetingParamName:
          Fn::Sub: /${AWS::StackName}/greeting
        FontsizeParamName:
          Fn::Sub: /${AWS::StackName}/fontSize
        TopicName:
          Fn::Sub: ${AWS::StackName}-ParamChanges
        EventRuleName:
          Fn::Sub: ${AWS::StackName}-ParamChangeRule
  DemoCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/micharizdemo-scratchbucket/e3a8862d29d1add940e57631b384a3e9.template
      Parameters:
        VpcId:
          Fn::GetAtt:
          - DemoVpc
          - Outputs.VpcId
        Prefix:
          Fn::Sub: ${AWS::StackName}
        ProxyImage: 845041152230.dkr.ecr.eu-west-1.amazonaws.com/rizblie/not_proxy
        GreetingImage: 845041152230.dkr.ecr.eu-west-1.amazonaws.com/rizblie/greeting
        ConfigVersionParamName:
          Fn::Sub: /${AWS::StackName}/configVersion
        ImageUrlParamName:
          Fn::Sub: /${AWS::StackName}/imageUrl
        GreetingParamName:
          Fn::Sub: /${AWS::StackName}/greeting
        FontsizeParamName:
          Fn::Sub: /${AWS::StackName}/fontSize
        TopicArn:
          Fn::GetAtt:
          - DemoSSMParams
          - Outputs.TopicArn
        PrivateSubnetIdA:
          Fn::GetAtt:
          - DemoVpc
          - Outputs.ZoneAPrivateSubnetId
        PrivateSubnetIdB:
          Fn::GetAtt:
          - DemoVpc
          - Outputs.ZoneBPrivateSubnetId
        PublicSubnetIdA:
          Fn::GetAtt:
          - DemoVpc
          - Outputs.ZoneAPublicSubnetId
        PublicSubnetIdB:
          Fn::GetAtt:
          - DemoVpc
          - Outputs.ZoneBPublicSubnetId
